#    Copyright 2021 Perpetual Intelligence L.L.C. All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0.
#    https://github.com/perpetualintelligence/terms/blob/main/LICENSE
#
#    Additional terms and policies.
#    https://github.com/perpetualintelligence/terms/blob/main/policies.md

# Builds, tests and publishes the packages to GitHub registry.

name: build-test-publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    # Specifiy the environment to read the pipeline metadata
    environment: PI_PROTOCOLS_ENV
    
    # Define package version
    env:
      PI_PACKAGE_VERSION: "${{ secrets.PI_MAJOR_VERSION }}.${{ secrets.PI_MAJOR_VERSION }}.${{ secrets.PI_BUILD_VERSION }}"            

    # OS/Platform
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Setup .Net with global.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
      
    # Build
    - name: Build
      run: dotnet build --no-restore
      
    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    # Pack Preview
    - name: Pack Preview
      if: github.ref_name == 'preview'
      run: |
        echo branch=$GITHUB_REF_NAME version=$PI_PACKAGE_VERSION version-suffix=preview.$GITHUB_RUN_ATTEMPT"
        dotnet pack -p:PackageVersion=$PI_PACKAGE_VERSION -c Release --nologo --no-restore -o _packages -v m --version-suffix "preview.$GITHUB_RUN_ATTEMPT" 
      
    # Pack Rc
    - name: Pack RC
      if: github.ref_name == 'rc'
      run: |
        echo branch=$GITHUB_REF_NAME version=$PI_PACKAGE_VERSION version-suffix=rc.$GITHUB_RUN_ATTEMPT
        dotnet pack -p:PackageVersion=$PI_PACKAGE_VERSION -c Release --nologo --no-restore -o _packages -v m --version-suffix "rc.$GITHUB_RUN_ATTEMPT" 
        
     # Pack Release
    - name: Pack Release
      if: github.ref_name == 'main'
      run: |
        echo branch=$GITHUB_REF_NAME version=$PI_PACKAGE_VERSION suffix=preview attempt-id="rc.$GITHUB_RUN_ATTEMPT"
        dotnet pack -p:PackageVersion=$PI_PACKAGE_VERSION -c Release --nologo --no-restore -o _packages -v m
    
    # Enumerate
    - name: Enumerate
      run : ls -l
      working-directory: _packages
