#    Copyright (c) Perpetual Intelligence L.L.C. All Rights Reserved.
#
#    For license, terms, and data policies, go to:
#    https://terms.perpetualintelligence.com

name: build-test-cross-manual

# Triggers
on:  
  workflow_dispatch:

jobs:
  ubunto:   
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    # Environment Variables
    env:     
      # GitHub package authentication
      PI_GITHUB_USERNAME_ENV: ${{ secrets.PI_GITHUB_USERNAME }}
      PI_GITHUB_PAT_ENV: ${{ secrets.PI_GITHUB_PAT }}
      PI_CI_REFERENCE: local
      
    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v2 

    # Setup .Net with global.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    # Restore dependencies
    - name: Restore
      run: dotnet restore
      
    # Build
    - name: Build
      run: dotnet build --no-restore
      
    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  macos:   
    runs-on: macos-latest
    timeout-minutes: 5
    
    # Environment Variables
    env:     
      # GitHub package authentication
      PI_GITHUB_USERNAME_ENV: ${{ secrets.PI_GITHUB_USERNAME }}
      PI_GITHUB_PAT_ENV: ${{ secrets.PI_GITHUB_PAT }}
      PI_CI_REFERENCE: local
      
    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v2 

    # Setup .Net with global.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    # Restore dependencies
    - name: Restore
      run: dotnet restore
      
    # Build
    - name: Build
      run: dotnet build --no-restore
      
    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  windows:   
    runs-on: windows-latest
    timeout-minutes: 5
    
    # Environment Variables
    env:     
      # GitHub package authentication
      PI_GITHUB_USERNAME_ENV: ${{ secrets.PI_GITHUB_USERNAME }}
      PI_GITHUB_PAT_ENV: ${{ secrets.PI_GITHUB_PAT }}
      PI_CI_REFERENCE: local
      
    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v2 

    # Setup .Net with global.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    # Restore dependencies
    - name: Restore
      run: dotnet restore
      
    # Build
    - name: Build
      run: dotnet build --no-restore
      
    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal