#    Copyright 2021 Perpetual Intelligence L.L.C. All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0.
#    https://github.com/perpetualintelligence/terms/blob/main/LICENSE
#
#    Additional terms and policies.
#    https://github.com/perpetualintelligence/terms/blob/main/policies.md

# This pipelinebuilds, tests and packs the protocol src projects. It does not publish any package.

name: build-test-pack-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:    
  
    # OS/Platform
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    
    # Setup Environment
    # Establish a unique build number for today YYMMDD{RUN_NUMBER}{RUN_ATTEMPT} e.g. 2201032602
    - name: Setup environment
      run: |
        cat .github/package_version.env >> $GITHUB_ENV
        echo "PI_BUILD_NUMBER=$(date +'%y%m%d')${{ github.run_number }}${{ github.run_attempt }}" >> $GITHUB_ENV
      continue-on-error: false
      
    # Setup versions
    # Establish CI package versions
    # Format: <package>.2.3.6-ci.202201032602
    - name: Setup environment
      run: |
        echo "PI_PACKAGE_VERSION=${{ env.PI_MAJOR_VERSION }}.${{ env.PI_MINOR_VERSION }}.${{ env.PI_BUILD_VERSION }}-${{ env.PI_CI_SUFFIX }}.${{ env.PI_BUILD_NUMBER }}" >> $GITHUB_ENV
      continue-on-error: false
    
    # Print all env
    - name: Print Environement
      if: ${{ false }}  # Debug
      run: env
    
    # Setup .Net with global.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    # Restore dependencies
    - name: Restore
      run: dotnet restore
      
    # Build
    - name: Build
      run: dotnet build --no-restore
      
    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal   
 
        
     # Pack
    - name: Pack
      run: |
        echo branch=${{ github.ref_name }} version=${{ env.PI_PACKAGE_VERSION }}
        dotnet pack -p:PackageVersion=${{ env.PI_PACKAGE_VERSION }} -c Release --nologo --no-restore -o _packages -v m 
    
    # Enumerate
    - name: Enumerate
      run : ls -l
      working-directory: _packages
